#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    throw new Exception('This has to be run from the command line');
}

require __DIR__ . '/vendor/autoload.php';

use Cli\App;
$app = new App();

$actionController = new \App\Controllers\CliActionController($app);

$app->registerController('basset', $actionController);
$app->registerController('foxterrier', $actionController);
$app->registerController('mops', $actionController);
$app->registerController('plushmops', $actionController);
$app->registerController('puddle', $actionController);
$app->registerController('sheepdog', $actionController);

$app->runCommand($argv);
